export const ACTION_SHOW_QR='ACTION_SHOW_QR';
export const ACTION_SHOW_INVOICE='ACTION_SHOW_INVOICE';
export const ACTION_SEND_INDEX='ACTION_SEND_INDEX';
export const ACTION_CLOSE_QR ='ACTION_CLOSE_QR';
export const ACTION_CLOSE_INVOICE ='ACTION_CLOSE_INVOICE';
export const ACTION_LIST_TABLE ='ACTION_LIST_TABLE';
export const ACTION_CHANGE_TABLE_STATUS ='ACTION_CHANGE_TABLE_STATUS';
export const ACTION_SEND_TABLE ='ACTION_SEND_TABLE';